Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SellingProducts.Models;
using SellingProducts.Repository.Base;

namespace SellingProducts.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IGenericRepository<Category> _repository;
        public CategoryController(IGenericRepository<Category> repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            return View(_repository.GetAll());
        }
        [Authorize]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                var c = new Category
                {
                    Name = category.Name,
                    Id = category.Id,
                };
                var categoryModel = _repository.Create(category);
                return RedirectToAction("Index");                
            }
            else
            {
                return View(category);
            }            
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            var cat = _repository.GetById(id);
            if (cat == null)
            {
                return View("Error");
            }
            var newCat = new Category
            {
                Name = cat.Name,
                Id = cat.Id,
            };
            return View(newCat);
        }
        [HttpPost]
        [Authorize]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                var c = new Category
                {
                    Name = category.Name,
                    Id = category.Id,
                };
                var categoryModel = _repository.Edit(category);
                return RedirectToAction("Index");
            }
            else
            {
                return View(category);
            }

        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            var c = _repository.GetById(id);
            _repository.Delete(c);
            return RedirectToAction("Index");
        }
        
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SellingProducts.Data;
using SellingProducts.Models;
using SellingProducts.Services.ProductServices;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace SellingProducts.Controllers
{    
    public class ProductsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IHostingEnvironment _host;
        private readonly IProductService _productService;

        public ProductsController(AppDbContext context , IHostingEnvironment host,IProductService productService)
        {
            _context = context;
            _host = host;
            this._productService = productService;
        }
        public IActionResult Index()
        {
            //IEnumerable<Product> productsList = _context.Products.Include(c => c.Category).ToList();
            var productList = _productService.GetAll();
            //Test
            return View(productList);
        }
        [Authorize]
        public IActionResult Create()
        {
            createSelectList();
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if (product.ClientFile != null)
                {
                    string myUpload = Path.Combine(_host.WebRootPath, "images");
                    fileName = product.ClientFile.FileName;
                    string fullPath = Path.Combine(myUpload, fileName);
                    product.ClientFile.CopyTo(new FileStream(fullPath,FileMode.Create));
                    product.Image = fileName;
                }

                _context.Products.Add(product);
                _context.SaveChanges();
                TempData["successData"] = "Item has been created";
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }
        [Authorize]
        public void createSelectList(int selectId = 0)
        {
            List<Category> categories = _context.Categories.ToList();
            SelectList listItems = new SelectList(categories,"Id","Name",selectId);
            ViewBag.CategoryList = listItems;
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            Product product =_context.Products.FirstOrDefault(c => c.Id == id)!;
            if (product == null)
            {
                 return NotFound();
            }

            _context.Products.Remove(product);
            _context.SaveChanges();
            TempData["errorData"] = "Item has been deleted";
            return RedirectToAction("Index");
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            var product = _context.Products.FirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            var productVM = new Product
            {
                Name = product.Name,
                Price = product.Price,
                Category = product.Category,
                CategoryId = product.CategoryId,
                CreatedDate = DateTime.Now,
            };
            createSelectList(product.CategoryId);
            return View(productVM);
        }
        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, Product product)
        {
            var products = _context.Products.FirstOrDefault(x => x.Id == id);
            if (products == null)
            {
                return NotFound();
            }
            products.Name = product.Name;
            products.Price = product.Price;
            products.Category = product.Category;
            products.CategoryId = product.CategoryId;
            products.CreatedDate = DateTime.Now;
            _context.SaveChanges();
            TempData["updatedData"] = "Item has been Updated";
            return RedirectToAction("Index");
        }
        
        public IActionResult Details(int id)
        {
            Product product =_context.Products.FirstOrDefault(x => x.Id == id)!;
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SellingProducts</title>
    <link rel="stylesheet" href="~/css/BootSwatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SellingProducts.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SellingProducts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Employees" asp-controller="Employees" asp-action="Index">Employees list</a>
                        </li>                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container"> 
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SellingProducts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notifications.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@if (TempData["successData"] != null)
{
    <h3 style="color:grey; font-family:Gabriola">
        @TempData["successData"]
    </h3>
    <script type="text/javascript">
        toastr.success('@TempData["successData"]', 'Added Successfully')')
    </script>
}

@if (TempData["errorData"] != null)
{
    <h3 style="color:grey; font-family:Gabriola">
        @TempData["errorData"]
    </h3>
    <script type="text/javascript">
        toastr.error('@TempData["errorData"]', 'Deleted Successfully')
    </script>
}

@if (TempData["updatedData"] != null)
{
    <h3 style="color:grey; font-family:Gabriola">
        @TempData["updatedData"]
    </h3>
    <script type="text/javascript">
        toastr.success('@TempData["updatedData"]', 'Updated Successfully')
    </script>
}